# Generated by Django 6.0 on 2025-12-18 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField(default=1, verbose_name='Hộp số (1-5)')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian ôn tới')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='Đã thuộc lòng')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú cá nhân')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chủ đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='topic_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Từ vựng')),
                ('phonetic', models.CharField(blank=True, max_length=100, verbose_name='Phiên âm')),
                ('definition', models.TextField(verbose_name='Định nghĩa')),
                ('example_sentence', models.TextField(blank=True, verbose_name='Câu ví dụ')),
                ('meaning_sentence', models.TextField(blank=True, verbose_name='Nghĩa câu ví dụ')),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocab_audio/', verbose_name='Audio mẫu')),
            ],
        ),
    ]
