# Generated by Django 6.0 on 2025-12-18 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notebookentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.topic'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='study.topic'),
        ),
        migrations.AddField(
            model_name='notebookentry',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.vocabulary'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.vocabulary'),
        ),
        migrations.AlterUniqueTogether(
            name='notebookentry',
            unique_together={('user', 'vocabulary')},
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('user', 'vocabulary')},
        ),
    ]
