# Generated by Django 6.0 on 2025-12-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='box',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='next_review',
        ),
    ]
