# Generated by Django 6.0 on 2025-12-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_remove_flashcard_box_remove_flashcard_next_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='is_mastered',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='mastery_level',
            field=models.IntegerField(default=0),
        ),
    ]
