# Generated by Django 6.0 on 2025-12-30 09:27

import django.db.models.deletion
import speaking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Câu mẫu (Tiếng Anh)')),
                ('translation', models.CharField(blank=True, max_length=500, verbose_name='Dịch nghĩa (Tiếng Việt)')),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=speaking.models.speaking_recording_path, verbose_name='File ghi âm')),
                ('overall_score', models.FloatField(default=0.0, verbose_name='Điểm tổng quan')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='Độ chính xác')),
                ('fluency_score', models.FloatField(default=0.0, verbose_name='Độ lưu loát')),
                ('completeness_score', models.FloatField(default=0.0, verbose_name='Độ hoàn thành')),
                ('api_response', models.JSONField(blank=True, default=dict, verbose_name='Phản hồi từ API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian luyện tập')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='speaking.speakingsentence', verbose_name='Câu đã luyện')),
            ],
            options={
                'verbose_name': 'Nhật ký phát âm',
                'verbose_name_plural': 'Danh sách nhật ký phát âm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề chủ đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='speaking_topics/', verbose_name='Hình ảnh minh họa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('users_who_saved', models.ManyToManyField(blank=True, related_name='saved_speaking_topics', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng đã lưu')),
            ],
        ),
        migrations.AddField(
            model_name='speakingsentence',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='speaking.speakingtopic', verbose_name='Chủ đề'),
        ),
    ]
