# Generated by Django 6.0 on 2025-12-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.CharField(max_length=500, verbose_name='Câu/Từ luyện tập')),
                ('audio_file', models.FileField(upload_to='speaking_recordings/', verbose_name='File ghi âm')),
                ('overall_score', models.FloatField(default=0.0, verbose_name='Điểm tổng quan')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='Độ chính xác')),
                ('fluency_score', models.FloatField(default=0.0, verbose_name='Độ lưu loát')),
                ('completeness_score', models.FloatField(default=0.0, verbose_name='Độ trọn vẹn')),
                ('api_response', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết từ Azure API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày luyện tập')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người học')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
