# Generated by Django 6.0 on 2025-12-22 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Câu mẫu (Tiếng Anh)')),
                ('translation', models.CharField(blank=True, max_length=500, verbose_name='Dịch nghĩa (Tiếng Việt)')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề chủ đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='speaking_topics/', verbose_name='Hình ảnh minh họa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pronunciationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nhật ký phát âm', 'verbose_name_plural': 'Danh sách nhật ký phát âm'},
        ),
        migrations.RemoveField(
            model_name='pronunciationlog',
            name='reference_text',
        ),
        migrations.AlterField(
            model_name='pronunciationlog',
            name='api_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Phản hồi từ API'),
        ),
        migrations.AlterField(
            model_name='pronunciationlog',
            name='completeness_score',
            field=models.FloatField(default=0.0, verbose_name='Độ hoàn thành'),
        ),
        migrations.AlterField(
            model_name='pronunciationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian luyện tập'),
        ),
        migrations.AlterField(
            model_name='pronunciationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='pronunciationlog',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='speaking.speakingsentence', verbose_name='Câu đã luyện'),
        ),
        migrations.AddField(
            model_name='speakingsentence',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='speaking.speakingtopic', verbose_name='Chủ đề'),
        ),
    ]
