# Generated by Django 6.0 on 2025-12-26 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0002_speakingsentence_speakingtopic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtopic',
            name='users_who_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
