# Generated by Django 6.0 on 2025-12-28 06:12

import speaking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0002_speakingsentence_speakingtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciationlog',
            name='audio_file',
            field=models.FileField(upload_to=speaking.models.speaking_recording_path, verbose_name='File ghi âm'),
        ),
    ]
