# Generated by Django 6.0 on 2025-12-29 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0003_alter_pronunciationlog_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtopic',
            name='users_who_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_speaking_topics', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng đã lưu'),
        ),
    ]
